name: dbt CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  dbt-build:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            dbt-core==1.9.4 \
            dbt-snowflake==1.9.2 \
            google-cloud-storage==2.19.0 \
            elementary-data==0.18.1 \
            pyarrow==18.1.0

      - name: Create dbt profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOF
          lapd_crime_project:
            target: dev
            outputs:
              dev:
                account: $SNOWFLAKE_ACCOUNT
                user: $SNOWFLAKE_USER
                password: $SNOWFLAKE_PASSWORD
                role: $SNOWFLAKE_ROLE
                database: $SNOWFLAKE_DATABASE
                warehouse: $SNOWFLAKE_WAREHOUSE
                schema: $SNOWFLAKE_SCHEMA
                threads: 4
          EOF

      - name: Run dbt build
        working-directory: ./airflow/dbt/lapd_crime_project
        run: dbt build --profiles-dir ~/.dbt
